name: Publish Container Images

#on: workflow_dispatch
  #release:
  #  types: [published] # todo - change this to trigger on other workflows
  #push:
  #  branches:
  #    - main
  #workflow_run:
  #  workflows: [Scala Build & Test]
  #  types:
  #    - completed
on:
  push:
    branches:  
      - "main"
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_run:
    workflows: ["Scala Build & Test"]
    types: [completed]
    branches: [main]
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    push_to_registry:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      permissions:
        packages: write
        contents: read
        attestations: write
        id-token: write
      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Checkout with LFS
          uses: actions/checkout@v4
          with:
            lfs: true
        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            java-version: '21'
            distribution: 'adopt-hotspot'
            cache: 'sbt'
        - name: Declare some variables
          shell: bash
          run: |
            echo "short_git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV" 
            echo "git_branch=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV" 
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}
        - name: Log in to Github Container Registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v5
          with:
            #images: spicelabs/goatrodeo
            images: |
              spicelabs/goatrodeo
              ghcr.io/${{ github.repository }}
            tags: |
              type=semver,pattern={{version}}
              type=semver,pattern={{major}}.{{minor}}
              type=semver,pattern={{major}}
              type=ref,event=branch
              type=ref,event=pr
              type=sha
              type=raw,value=latest,enable={{is_default_branch}}

        - name: Stage Docker build environment from sbt
          run: |
            sbt Docker/stage
        - name: Build and Push
          id: push
          uses: docker/build-push-action@v6
          with:
            context: target/docker/stage
            push: true
            provenance: mode=max
            sbom: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }} 
        - name: Generate artifact attestation
          uses: actions/attest-build-provenance@v1
          with:
            subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            subject-digest: ${{ steps.push.outputs.digest }}
            push-to-registry: true
